export declare const wt: {
    request: (opts: any) => Promise<any>;
    chooseImage: (opts: any) => Promise<any>;
    previewImage: (opts: any) => Promise<any>;
    getImageInfo: (opts: any) => Promise<any>;
    saveFile: (opts: any) => Promise<any>;
    getSavedFileList: (opts: any) => Promise<any>;
    getSavedFileInfo: (opts: any) => Promise<any>;
    removeSavedFile: (opts: any) => Promise<any>;
    openDocument: (opts: any) => Promise<any>;
    setStorage: (opts: any) => Promise<any>;
    getStorage: (opts: any) => Promise<any>;
    getStorageInfo: (opts: any) => Promise<any>;
    removeStorage: (opts: any) => Promise<any>;
    clearStorage: any;
    getLocation: (opts: any) => Promise<any>;
    chooseLocation: (opts: any) => Promise<any>;
    openLocation: (opts: any) => Promise<any>;
    createMapContext: any;
    getSystemInfo: (opts: any) => Promise<any>;
    getNetworkType: (opts: any) => Promise<any>;
    makePhoneCall: (opts: any) => Promise<any>;
    scanCode: (opts: any) => Promise<any>;
    setClipboardData: (opts: any) => Promise<any>;
    getClipboardData: (opts: any) => Promise<any>;
    showToast: (opts: any) => Promise<any>;
    hideToast: any;
    showModal: (opts: any) => Promise<any>;
    showActionSheet: (opts: any) => Promise<any>;
    setNavigationBarTitle: (opts: any) => Promise<any>;
    showNavigationBarLoading: any;
    hideNavigationBarLoading: any;
    navigateTo: (opts: any) => Promise<any>;
    redirectTo: (opts: any) => Promise<any>;
    switchTab: (opts: any) => Promise<any>;
    navigateBack: (opts: any) => Promise<any>;
    stopPullDownRefresh: any;
    login: (opts: any) => Promise<any>;
    checkSession: (opts: any) => Promise<any>;
    getUserInfo: (opts: any) => Promise<any>;
    requestPayment: (opts: any) => Promise<any>;
};
