export * from './decorators/app.decor'
export * from './decorators/page.decor'
export * from './decorators/component.decor'
export * from './lib/wx'
export * from './lib/page'
export * from './lib/app'
export * from './lib/component'
export * from '../typings/wetype'